version: "3"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_notebook # Assign a custom name to the container
    image: jupyter_env
    command: start-notebook.sh --NotebookApp.token=''
    ports:
      - "8888:8888" # Map Jupyter Notebook port from container to host
    volumes:
      - ../:/home/jovyan/work # Map local "notebooks" directory to Jupyter workspace
