version: "1"

services:
  notebook:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/notebooks
    environment:
      - NB_USER=jovyan
      - NB_UID=1000
      - NB_GID=100
