repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: debug-statements
      - id: detect-private-key
      - id: pretty-format-json
        args: ["--autofix"]

  - repo: https://github.com/myint/autoflake
    rev: v2.0.1
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --ignore-init-module-imports
          - --remove-all-unused-imports
          - --expand-star-imports
          - --remove-duplicate-keys
          - --remove-unused-variables
          - --verbose

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E203,W503
          - --max-line-length=79
          - --max-doc-length=72

  - repo: https://github.com/PyCQA/pylint
    rev: v2.16.2
    hooks:
      - id: pylint
        files: ".ipynb"
        additional_dependencies:
          - nbformat
          - pyyaml
        args:
          - --disable=broad-except
          - --disable=line-too-long
          - --disable=too-many-instance-attributes
          - --disable=too-many-nested-blocks
          - --disable=too-many-public-methods
          - --disable=too-many-statements
          - --disable=unused-argument
          - --disable=unused-variable

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.0.1
    hooks:
      - id: mypy
        args:
          - --ignore-missing-imports
        additional_dependencies:
          - types-dateparser
          - types-requests
          - types-six
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, html, yaml]

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle

  # Jupyter Notebook checks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 0.7.0
    hooks:
      #- id: nbqa-black
      #  additional_dependencies: [black==20.8b1]
      #  args: [--nbqa-mutate]
      - id: nbqa-flake8
        additional_dependencies: [flake8]
        args: [--nbqa-mutate]
      - id: nbqa-isort
        additional_dependencies: [isort==5.7.0]
        args: [--nbqa-mutate]

  # Latex checks
  - repo: https://github.com/jonasbb/pre-commit-latex-hooks
    rev: v1.4.0
    hooks:
      - id: american-eg-ie
      - id: cleveref-capitalization
      - id: consistent-spelling
        args:
          [
            "--emph=et al.",
            "--emph=a priori",
            "--emph=a posteriori",
            '--regex=naive=\bna(i|\\"i)ve',
          ]
      - id: csquotes
      - id: ensure-labels-for-sections
      - id: no-space-in-cite
      - id: tilde-cite
      - id: unique-labels
        # args:
        #     [
        #       # If present only check that there is a \label{} but not the value
        #       "--ignore-label-content",
        #     ]
      - id: cleveref-instead-of-autoref
