version: "3"

services:
  notebook:
    image: continuumio/miniconda3:latest
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/notebooks
    environment:
      - NB_USER=jovyan
      - NB_UID=1000
      - NB_GID=100
    command: >
      bash -c "conda create -n myenv python=3.11 && \
      conda activate myenv && \
      conda install -c conda-forge jupyterlab && \
      conda install -c conda-forge mathjax && \
      jupyter labextension install @jupyterlab/latex && \
      jupyter labextension install @jupyterlab/latex-unicode && \
      jupyter labextension install @jupyterlab/equation-numbering && \
      jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''"
