version: "3"

services:
  notebook:
    image: continuumio/miniconda3:latest
    ports:
      - 8888:8888
    volumes:
      - ./:/home/jovyan/notebooks
    command: bash -c "conda install -c conda-forge jupyterlab && jupyter lab --ip=0.0.0.0 --allow-root --NotebookApp.token=''"

    # Install LaTeX support packages
    environment:
      - NB_USER=jovyan
      - NB_UID=1000
      - NB_GID=100
