version: "1.0.0"
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      #- "8888:8888"
      - target: 8888
        published: 8888
    volumes:
      - type: bind
        source: ./notebooks
        target: /home/jovyan/work/notebooks
    #command: start-notebook.sh --NotebookApp.notebook_dir=/home/jovyan/work/notebooks
